        name: Java Release

        on:
          workflow_dispatch:


        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            

    #---------------- Build Script
          BUILD_SCRIPT:
            needs: [build]
            runs-on: ubuntu-latest
            steps:
               - name: Run script on the VM
                 run: |
                   sshpass -p "test" ssh -o StrictHostKeyChecking=no test@192.168.1.56 <<EOF
                              cd my-java-project
                              git init
                              git add .
                              git commit -m "Initial commit"
                              git branch -M main
                              git remote add origin https://github.com/yourusername/my-java-project.git
                              git push -u origin main
                               
                   EOF

    #---------------- Sonarqube
          SONARQUBE:
            needs: [BUILD_SCRIPT]
            runs-on: ubuntu-latest
            environment:
              name: STAGING
            steps:
              - uses: actions/checkout@master
              - name: SonarQube Scan
                uses: sonarsource/sonarqube-scan-action@master
            env:
                SONAR_TOKEN: squ_8c5e7438e05474ebcb879b70892d439619fe4daa
                SONAR_HOST_URL: http://158.220.107.63:9000/
 
    #---------------- Orchestration 
          ORCHESTRATION:
            needs: [SONARQUBE]
            runs-on: ubuntu-latest
            permissions:
               issues: write
            steps:
               - uses: trstringer/manual-approval@v1
                 with:
                   secret: ${{ secrets.GITHUB_TOKEN }}
                   approvers: suriyakanth1
                   issue-title: "Orchestration"
                   issue-body: "run_id: ${{ github.run_id }}"